apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilender-prod
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ilender-prod-ns
    name: in-cluster
  project: default
  source:
    path: prod
    repoURL: https://github.com/GandhiCloudLab/argo-app-ilender
    targetRevision: HEAD