apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilender-dev
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ilender-dev-ns
    name: in-cluster
  project: default
  source:
    path: dev
    repoURL: https://github.com/GandhiCloudLab/argo-app-ilender
    targetRevision: HEAD