apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilender-stage
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ilender-stage-ns
    name: in-cluster
  project: default
  source:
    path: stage
    repoURL: https://github.com/GandhiCloudLab/argo-app-ilender
    targetRevision: HEAD